server:
  owner: Owner
  root: http://localhost:8083
songs:
  prefix: /public/songs/
  pieces:
    - name: 光るなら
      artist: Goose House
      url: hikarunara.mp3
      cover:
      lrc: hikarunara.lrc
