server:
  owner: Owner
  root: http://localhost:8083
  cdn:
    aplayer: https://cdn.jsdelivr.net/npm/{pkg}@{ver}/dist/{filename}
songs:
  prefix: /public/songs/
  pieces:
    - name: 光るなら
      artist: Goose House
      url: hikarunara.mp3
      cover:
      lrc: hikarunara.lrc
