server:
  owner: Owner
  root: http://localhost:8083
songs:
  pieces:
    - name: 光るなら
      artist: Goose House
      url: /public/songs/hikarunara.mp3
      cover:
      lrc: /public/songs/hikarunara.lrc
